apiVersion: apps/v1
kind: Deployment
metadata:
  name: forecast-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: forecast-app
  template:
    metadata:
      labels:
        app: forecast-app
    spec:
      hostname: forecast-app
      containers:
      - name: forecast-app
        image: jardelkuhnen/forecast-app:latest
        resources:
          requests:
              cpu: 100m
              memory: 100Mi
          limits:
              memory: 2048Mi
              cpu: 500m
        ports:
        - containerPort: 8080
          name: http
        env: 
          - name: spring.profile.active
            valueFrom:
              secretKeyRef:
                key: profile_active
                name: forecast-app 
          - name: spring.datasource.url
            valueFrom:
              secretKeyRef:
                key: database_url
                name: forecast-app 
          - name: spring.datasource.user
            valueFrom:
              secretKeyRef:
                key: database_user
                name: forecast-app   
          - name: app.openweather.apikey
            valueFrom:
              secretKeyRef:
                key: openweather_apikey
                name: forecast-app   
---

apiVersion: v1
kind: Service
metadata:
  name: forecast-app
spec:
  type: ClusterIP
  selector:
    app: forecast-app
  ports:
  - name: http
    port: 8080
    targetPort: 8080

---
apiVersion: v1
kind: Secret
metadata:
  name: forecast-app
type: Opaque
data:
  profile_active: cHJvZA==
  database_url: amRiYzpoMjptZW06aGJzaXNGb3JlY2FzdA==
  database_user: c2E=
  openweather_apikey: ZWI4YjFhOTQwNWU2NTliMmZmYzc4ZjBhNTIwYjFhNDY=
